#!/bin/sh

docker run --name some-mysql \
  -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD=${MYSQL_LOCAL_ROOT_PASSWORD} \
  -e MYSQL_DATABASE=${MYSQL_LOCAL_DATABASE} \
  -e MYSQL_HOST=${MYSQL_LOCAL_HOST} \
  -e MYSQL_PORT=${MYSQL_LOCAL_PORT} \
  -e MYSQL_USER=${MYSQL_LOCAL_USER} \
  -e MYSQL_PASSWORD=${MYSQL_LOCAL_PASSWORD} \
  -d mysql:${MYSQL_LOCAL_VERSION}